---
resources:
- name: concourse-docker-test
  type: git
  source:
    uri: https://github.com/iamroddo/concourse-docker-test.git
    branch: master
    username: ((git-username))
    password: ((git-password))

- name: docker-image
  type: docker-image
  source:
    host: ((docker-host))
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-repository))
    tag: 'version'

- name: version
  type: semver
  source:
    driver: git
    uri: https://github.com/iamroddo/concourse-docker-test.git
    branch: master
    username: ((git-username))
    password: ((git-password))
    file: version

jobs:
- name: version-up
  serial: true
  plan:
  - get: concourse-docker-test
    trigger: true
  - put: version
    params:
      bump: minor

- name: publish
  serial: true
  plan:
  - get: concourse-docker-test
  - get : version
    trigger: true
  - put: docker-image
    params:
      build: concourse-docker-test/.
      tag: concourse-docker-test/version
